on:
  workflow_dispatch:
    inputs:
      crate:
        description: 'Crate to release'
        required: true
        default: 'ngrok'
      message:
        description: 'Tag message'
        required: false

name: Release

jobs:
  udeps:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - uses: jrobsonchase/direnv-action@v0.6
      - uses: actions-rs/cargo@v1
        name: semver checks
        with:
          command: semver-checks
          args: check-release -p ${{ inputs.crate }}
      - run: |
          version=$(extract-version ${{inputs.crate}})
          if [[ "${{ inputs.message }}" ]]; then
            git tag -a -m "${{ inputs.message }}" v${version}
          else
            git tag -a -m "Version ${version}" v${version}
          fi