on:
  workflow_dispatch:
    inputs:
      crate:
        description: 'Crate to release'
        required: true
        default: 'ngrok'
      message:
        description: 'Tag message'
        required: false

name: Release

jobs:
  semver:
    name: Semver Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - uses: jrobsonchase/direnv-action@v0.6
      - uses: actions-rs/cargo@v1
        name: semver checks
        with:
          command: semver-checks
          args: check-release -p ${{ inputs.crate }}

  dry-publish:
    name: Dry Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - uses: jrobsonchase/direnv-action@v0.6
      - name: cargo publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p ${{ inputs.crate }} --dry-run

  cargo-publish:
    name: Publish and Tag
    runs-on: ubuntu-latest
    needs: [semver, dry-publish]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - uses: jrobsonchase/direnv-action@v0.6
      - name: cargo publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p ${{ inputs.crate }} --token ${{secrets.CARGO_REGISTRY_TOKEN}}
      - name: tag release
        run: |
          version="$(extract-crate-version ${{inputs.crate}})"
          git config user.name "GitHub Action"
          git config user.email noreply@ngrok.com
          git tag -a -m "Version ${version}" ${{inputs.crate}}-v${version}
          git push --tags